### ISSUE TITLE
Check Management Plugin

### ISSUE THREAD

**Issue by s-newman** [scorestack/scorestack#190]
**What do you want ScoreStack to do that it cannot currently do?**
A user interface should be provided for adding and removing checks to a running instance of ScoreStack.

**How would you like ScoreStack to do that?**
A custom Kibana plugin should be written to allow administrators to create and modify check templates and attribute definitions.

- [ ] Create a static template administration application (#217)
- [ ] Create an API for reading, creating, modifying, and deleting templates (#218)
- [ ] Hook up the template application to the template API (#219)
- [ ] Overhaul the attribute API to allow for reading, creation, modification, and deletion (#220)
- [ ] Overhaul the attribute application to allow administrators to create, modify, and delete checks & attributes (#221)

**Comment by s-newman** [comment]
Closing in favor of #262.
